site_name: TTNRT Docs
repo_url: https://github.com/TTNRT/docswebsite
edit_uri: edit/main/docs/
repo_name: TTNRT/docswebsite

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - toc.follow
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top

markdown_extensions:
    - toc:
        permalink: '#'
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences

plugins:
  - search

copyright: >
  Copyright &copy; 2020 - 2024 TTNRT Corporation

extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: https://feedback.ttnrtsite.me
      name: Feedback
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
nav:
  - Home: index.md
  - Assist AI:
    - FAQ: assistai/faq.md
  - TTGit:
    - Customize your profile: ttgit/customizeprofile.md
    - Setup Git client: ttgit/gitclient.md
    - Bring a local folder: ttgit/bringlocalfolder.md
    - Using an IDE editor: ttgit/ideeditor.md
    - Using the actions interface: ttgit/actionssetup.md
    - Using Woodpecker CI: ttgit/woodpeckerci.md
  - myTT:
    - Creating your account: mytt/accountcreate.md
    - Customizing your profile: mytt/profilecustomize.md
    - Account profile: mytt/accountprofile.md